import t1 from './images/Tiles/Thesis.jpg';
import t2 from './images/Tiles/UD.jpg';
import t3 from './images/Tiles/Skjn.jpg';
import t4 from './images/Tiles/OMA.jpg';
import t5 from './images/Tiles/NG.jpg';
import t6 from './images/Tiles/AIPlants.jpg';
import t7 from './images/Tiles/Housing.jpg';
import t8 from './images/Tiles/DFH.jpg';
import t9 from './images/Tiles/BITS.jpg';
import th1 from './images/Thesis/1.jpg';
import th2 from './images/Thesis/2.jpg';
import th3 from './images/Thesis/3.jpg';
import th4 from './images/Thesis/4.jpg';
import th5 from './images/Thesis/5.jpg';
import th6 from './images/Thesis/6.jpg';
import th7 from './images/Thesis/7.jpg';
import th8 from './images/Thesis/8.jpg';
import th9 from './images/Thesis/9.jpg';
import ng1 from './images/NG/1.jpg';
import ng2 from './images/NG/2.jpg';
import ng3 from './images/NG/3.jpg';
import ng4 from './images/NG/4.jpg';
import ng5 from './images/NG/5.jpg';
import ud1 from './images/UD/1.jpg';
import ud2 from './images/UD/2.jpg';
import ud3 from './images/UD/3.jpg';
import ud4 from './images/UD/4.jpg';
import ud5 from './images/UD/5.jpg';
import ud6 from './images/UD/6.jpg';
import ud7 from './images/UD/7.jpg';
import ud8 from './images/UD/8.jpg';
import ud9 from './images/UD/9.jpg';
import ud10 from './images/UD/10.jpg';
import ud11 from './images/UD/11.jpg';
import ud12 from './images/UD/12.jpg';
import ud13 from './images/UD/13.jpg';
import h1 from './images/Housing/1.jpg'
import h2 from './images/Housing/1a.jpg'
import h3 from './images/Housing/2.jpg'
import h4 from './images/Housing/3.jpg'
import h5 from './images/Housing/4.jpg'
import h6 from './images/Housing/5.jpg'
import avatar1 from './images/Display.png'
import om1 from './images/OMA/1.jpg'
import om2 from './images/OMA/2.jpg'
import om3 from './images/OMA/3.jpg'
import bt1 from './images/BITS/1.jpg'
import bt2 from './images/BITS/2.jpg'
import resume from './images/Resume.pdf';
import sk1 from './images/Skjn/2.jpg';
import sk2 from './images/Skjn/3.jpg';
import sk3 from './images/Skjn/4.jpg';
import sk4 from './images/Skjn/5.jpg';
import dfh1 from './images/DFH/1.jpg';
import dfh2 from './images/DFH/Sensei.pdf';
import dfh3 from './images/DFH/3.jpg';
import dfh4 from './images/DFH/4.jpg';
import dfh5 from './images/DFH/5.jpg';
import dfh6 from './images/DFH/6.png';
import dfh7 from './images/DFH/7.png';
import dfh8 from './images/DFH/8.jpg';
import dfh9 from './images/DFH/9.jpg';
import dfh11 from './images/DFH/11A.jpg';
import dfh12 from './images/DFH/12.png';
import dfh13 from './images/DFH/13.png';
import dfh14 from './images/DFH/14.png';
import dfh15 from './images/DFH/15.png';
import dfh16 from './images/DFH/16.jpg';
import dfh17 from './images/DFH/17.jpg';
import dfh18 from './images/DFH/18.jpg';
import dfh19 from './images/DFH/19.jpg';
import dfh20 from './images/DFH/20.jpg';
import dfh21 from './images/DFH/21.jpg';
import dfh22 from './images/DFH/22.jpg';
import dfh23 from './images/DFH/23.jpg';
import dfh24 from './images/DFH/24.jpg';
import dfh25 from './images/DFH/25.jpg';
import dfh26 from './images/DFH/26.jpg';
import dfh27 from './images/DFH/27.jpg';
import dfh28 from './images/DFH/28.png';
import dfh29 from './images/DFH/29.png';
import dfh30 from './images/DFH/30.png';
import dfh34 from './images/DFH/34.png';
import dfh35 from './images/DFH/35.png';
import dfh36 from './images/DFH/36.png';
import dfh37 from './images/DFH/37.png';
import dfh31 from './images/DFH/31.jpg';
import dfh32 from './images/DFH/32.jpg';
import dfh33 from './images/DFH/11B.jpg';
import dfh38 from './images/DFH/38.jpg';
import dfh39 from './images/DFH/39.jpg';
import dfh40 from './images/DFH/40.png';
import dfh41 from './images/DFH/41.jpg';
import dfh42 from './images/DFH/42.jpg';
import dfh43 from './images/DFH/43.jpg';
import dfh44 from './images/DFH/44.jpg';
import dfh45 from './images/DFH/45.jpg';
import dfh46 from './images/DFH/46.jpg';
import dfh47 from './images/DFH/47.jpg';
import am1 from './images/Display2.png';
import om4 from './images/OMA/4.jpg';
import om5 from './images/OMA/5.jpg';
import om6 from './images/OMA/6.jpg';
import om7 from './images/OMA/7.jpg';
import om8 from './images/OMA/8.jpg';
import om9 from './images/OMA/9.jpg';
import dfh48 from './images/DFH/48.jpg';
import om10 from './images/OMA/10.jpg';
import dfh49 from './images/DFH/49.jpg';
import dfh50 from './images/DFH/50.png';
import dfh51 from './images/DFH/51.png';
import dfh52 from './images/DFH/52.png';
import dfh53 from './images/DFH/53.png';
import ai1 from './images/AI/1.jpg';
import ai2 from './images/AI/2.jpg';
import ai3 from './images/AI/3.jpg';
import ai4 from './images/AI/4.jpg';
import ai5 from './images/AI/5.jpg';
import ai6 from './images/AI/6.jpg';
import ai7 from './images/AI/7.jpg';
import ai8 from './images/AI/8.jpg';
import ai9 from './images/AI/9.jpg';
import ai10 from './images/AI/10.jpg';
import ai11 from './images/AI/11.jpg';
import ai12 from './images/AI/12.jpg';
import ai13 from './images/AI/13.jpg';
import ai14 from './images/AI/14.jpg';
import ai15 from './images/AI/15.jpg';
import ai16 from './images/AI/16.jpg';
import ai17 from './images/AI/17.jpg';
import ai18 from './images/AI/18.jpg';
import ai19 from './images/AI/19.jpg';
import ai20 from './images/AI/20.jpg';
import ai21 from './images/AI/21.jpg';
import ai22 from './images/AI/22.jpg';
import ai23 from './images/AI/23.jpg';
import ai24 from './images/AI/24.jpg';
import ai25 from './images/AI/25.jpg';
import ai26 from './images/AI/26.png';







export default [t1,t2,t3,t4,t5,t6,t7,t8,t9,th1,th2,th3,th4,th5,th6,th7,th8,th9,ng1,ng2,ng3,ng4,ng5,
                ud1,ud2,ud3,ud4,ud5,ud6,ud7,ud8,ud9,ud10,ud11,ud12,ud13,h1,h2,h3,h4,h5,h6,avatar1,
                om1,om2,om3,bt1,bt2,resume,sk1,sk2,sk3,sk4,dfh1,dfh2,dfh3,dfh4,dfh5,dfh6,dfh7,dfh8,
                dfh9,dfh11,dfh12,dfh13,dfh14,dfh15,dfh16,dfh17,dfh18,dfh19,dfh20,dfh21,dfh22,dfh23,dfh24,dfh25,dfh26,dfh27,dfh28,dfh29,dfh30,
                dfh34,dfh35,dfh36,dfh37,dfh31,dfh32,dfh33,dfh38,dfh39,dfh40,dfh41,dfh42,dfh43,dfh44,dfh45,dfh46,dfh47,am1,
                om4,om5,om6,om7,om8,om9,dfh48,om10,dfh49,dfh50,dfh51,dfh52,dfh53,ai1,ai2,ai3,ai4,ai5,ai6,ai7,ai8,ai9,ai10,ai11,ai12
                ,ai13,ai14,ai15,ai16,ai17,ai18,ai19,ai20,ai21,ai22,ai23,ai24,ai25,ai26]