import t1 from './images/Tiles/Thesis.jpg';
import t2 from './images/Tiles/UD.jpg';
import t3 from './images/Tiles/Skjn.jpg';
import t4 from './images/Tiles/OMA.jpg';
import t5 from './images/Tiles/NG.jpg';
import t6 from './images/Tiles/Illustrations.jpg';
import t7 from './images/Tiles/Housing.jpg';
import t8 from './images/Tiles/DFH.jpg';
import t9 from './images/Tiles/BITS.jpg';
import th1 from './images/Thesis/1.jpg';
import th2 from './images/Thesis/2.jpg';
import th3 from './images/Thesis/3.jpg';
import th4 from './images/Thesis/4.jpg';
import th5 from './images/Thesis/5.jpg';
import th6 from './images/Thesis/6.jpg';
import th7 from './images/Thesis/7.jpg';
import th8 from './images/Thesis/8.jpg';
import th9 from './images/Thesis/9.jpg';
import ng1 from './images/NG/1.jpg';
import ng2 from './images/NG/2.jpg';
import ng3 from './images/NG/3.jpg';
import ng4 from './images/NG/4.jpg';
import ng5 from './images/NG/5.jpg';
import ud1 from './images/UD/1.jpg';
import ud2 from './images/UD/2.jpg';
import ud3 from './images/UD/3.jpg';
import ud4 from './images/UD/4.jpg';
import ud5 from './images/UD/5.jpg';
import ud6 from './images/UD/6.jpg';
import ud7 from './images/UD/7.jpg';
import ud8 from './images/UD/8.jpg';
import ud9 from './images/UD/9.jpg';
import ud10 from './images/UD/10.jpg';
import ud11 from './images/UD/11.jpg';
import ud12 from './images/UD/12.jpg';
import ud13 from './images/UD/13.jpg';
import h1 from './images/Housing/1.jpg'
import h2 from './images/Housing/1a.jpg'
import h3 from './images/Housing/2.jpg'
import h4 from './images/Housing/3.jpg'
import h5 from './images/Housing/4.jpg'
import h6 from './images/Housing/5.jpg'
import d1 from './images/Display.png'
import om1 from './images/OMA/1.jpg'
import om2 from './images/OMA/2.jpg'
import om3 from './images/OMA/3.jpg'
import bt1 from './images/BITS/1.jpg'
import bt2 from './images/BITS/2.jpg'
import resume from './images/Resume.pdf';
import sk1 from './images/Skjn/2.jpg';
import sk2 from './images/Skjn/3.jpg';
import sk3 from './images/Skjn/4.jpg';
import sk4 from './images/Skjn/5.jpg';
import dfh1 from './images/DFH/1.jpg';
import dfh2 from './images/DFH/Sensei.pdf';
import dfh3 from './images/DFH/3.jpg';
import dfh4 from './images/DFH/4.jpg';
import dfh5 from './images/DFH/5.png';
import dfh6 from './images/DFH/6.jpg';
import dfh7 from './images/DFH/7.jpg';
import dfh8 from './images/DFH/8.jpg';
import dfh9 from './images/DFH/9.jpg';
import dfh11 from './images/DFH/11.jpg';
import dfh12 from './images/DFH/12.png';
import dfh13 from './images/DFH/13.png';
import dfh14 from './images/DFH/14.png';
import dfh15 from './images/DFH/15.png';
import dfh16 from './images/DFH/16.jpg';
import dfh17 from './images/DFH/17.jpg';
import dfh18 from './images/DFH/18.jpg';


export default [t1,t2,t3,t4,t5,t6,t7,t8,t9,th1,th2,th3,th4,th5,th6,th7,th8,th9,ng1,ng2,ng3,ng4,ng5,
                ud1,ud2,ud3,ud4,ud5,ud6,ud7,ud8,ud9,ud10,ud11,ud12,ud13,h1,h2,h3,h4,h5,h6,d1,
                om1,om2,om3,bt1,bt2,resume,sk1,sk2,sk3,sk4,dfh1,dfh2,dfh3,dfh4,dfh5,dfh6,dfh7,dfh8,
                dfh9,dfh11,dfh12,dfh13,dfh14,dfh15,dfh16,dfh17,dfh18]